####Nested Template For Creating an ALB for SDP
AWSTemplateFormatVersion: "2010-09-09"
Resources:
####Create ALB
  SDPALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: SDP-ECS-ALB
      Scheme: internal
      SecurityGroups: 
        - sg-052c5a74
        - sg-6e8a1510
      Subnets: 
        - subnet-4b539267
        - subnet-afc8fcca
      Type: application
####Create ALB Listener
  SDPALBListener:
   Type: AWS::ElasticLoadBalancingV2::Listener
   Properties:
     Certificates:
       - CertificateArn: arn:aws:acm:us-east-1:686883784036:certificate/54e40b36-1e94-43f1-977f-8b2b748c14c5
     DefaultActions:
       - Type: forward
         TargetGroupArn: !Ref 'SonarqubeTG'
     LoadBalancerArn: !Ref SDPALB
     Port: 443
     Protocol: "HTTPS"
#####Create Sonarqube Target Group
  SonarqubeTG:
   Type: AWS::ElasticLoadBalancingV2::TargetGroup
   DependsOn: 
    - SDPALB
   Properties: 
     HealthCheckEnabled: true
     HealthCheckIntervalSeconds: 10
     HealthCheckPath: /sonarqube
     HealthCheckPort: traffic-port
     HealthCheckProtocol: HTTP
     HealthCheckTimeoutSeconds: 5
     HealthyThresholdCount: 5
     Name: SDPSonarqubeTG
     Port: 80
     Protocol: HTTP
     UnhealthyThresholdCount: 2
     VpcId: vpc-8443b4fd
#####Create ALB Listener
  ECSALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: SDPALBListener
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'SonarqubeTG'
      Conditions:
      - Field: path-pattern
        Values: [/sonarqube]
      ListenerArn: !Ref 'SDPALBListener'
      Priority: 1
Outputs:
  SonarqubeTargetGroup:
    Value: !Ref 'SonarqubeTG'