####Jenkins Nested Template for SDP-Master 
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SDPCluster:
    Type: String
  JenkinsTG:
    Type: String
  DNSName: 
    Type: String
Resources:
  JenkinsMasterTskDefn:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      RequiresCompatibilities:
        - 'EC2'
      ContainerDefinitions:
        - 
          Name: 'jenkins-master-container'
          Image: '686883784036.dkr.ecr.us-east-1.amazonaws.com/tristan-test-repo:latest'
          Cpu: '2048'
          Memory: '3000'
          Essential: true
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
            - ContainerPort: 50000
              HostPort: 50000
          Environment:
            - Name: 'JENKINS_OPTS'
              Value: '--prefix=/jenkins'
      ExecutionRoleArn: 'arn:aws:iam::686883784036:role/BAHServiceRoleForECSTaskExecution'
      Memory: '8192'
      NetworkMode: 'bridge'
      TaskRoleArn: 'arn:aws:iam::686883784036:role/BAHServiceRoleForECSTaskExecution'
  JenkinsAgentTskDefn:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      RequiresCompatibilities:
        - 'EC2'
      ContainerDefinitions:
        - 
          Name: 'jenkins_agent-container'
          Image: '686883784036.dkr.ecr.us-east-1.amazonaws.com/tristan-test-repo:jenkins-agent'
          Cpu: '2048'
          Memory: '3000'
          Essential: true
          Environment:
            - Name: 'EXECUTORS'
              Value: '1'
            - Name: 'JENKINS_PASSWORD'
              Value: 'admin'
            - Name: 'JENKINS_USERNAME'
              Value: 'admin'
            - Name: 'JENKINS_URL'
              Value: !Sub '${DNSName}/jenkins'
      ExecutionRoleArn: 'arn:aws:iam::686883784036:role/BAHServiceRoleForECSTaskExecution'
      Memory: '8192'
      NetworkMode: 'bridge'
      TaskRoleArn: 'arn:aws:iam::686883784036:role/BAHServiceRoleForECSTaskExecution'
  JenkinsMasterservice:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'SDPCluster'
      DesiredCount: '1'
      TaskDefinition: !Ref JenkinsMasterTskDefn
      LoadBalancers:
        - ContainerName: jenkins-master-container
          ContainerPort: '8080'
          TargetGroupArn: !Ref JenkinsTG
    DependsOn:
      - JenkinsMasterTskDefn
  JenkinsAgentservice:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'SDPCluster'
      DesiredCount: '1'
      TaskDefinition: !Ref JenkinsAgentTskDefn
    DependsOn:
      - JenkinsAgentTskDefn