AWSTemplateFormatVersion: 2010-09-09
Resources:
###Task & Execution Role
  SDPContainerRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs-tasks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      MaxSessionDuration: 3600
      RoleName: SDPExecutionRole
### IAM Instance profile/ServiceRole
  SDPExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: {
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      MaxSessionDuration: 3600
      RoleName: SDPServiceRole
Outputs:
  SDPExecutionRole:
    Value: !GetAtt SDPExecutionRole
  SDPServiceRole:
    Value: !GetAtt SDPServiceRole
