{{- $root := . }}
{{- if and (.Values.master.JCasC.enabled) (.Values.master.sidecars.configAutoReload.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.master.secretsFilesSecret }}
  namespace: {{ template "jenkins.namespace" $root }}
  labels:
    "app.kubernetes.io/name": {{ template "jenkins.name" $root}}
    "helm.sh/chart": {{ $.Chart.Name }}-{{ $.Chart.Version }}
    "app.kubernetes.io/managed-by": "{{ $.Release.Service }}"
    "app.kubernetes.io/instance": "{{ $.Release.Name }}"
    "app.kubernetes.io/component": "{{ $.Values.master.componentName }}"
data:
  {{- range $key, $val := .Values.master.secretCredentials }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}

{{- end }}
