apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "sonarqube.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "sonarqube.name" . }}
        release: {{ .Release.Name }}
{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{ if .Values.annotations}}
      annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
    spec:
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      initContainers:
#        - name: init-sysctl
#          image: busybox:1.31
#          command:
#          - sysctl
#          - -w
#          - vm.max_map_count=262144
#          imagePullPolicy: IfNotPresent
#          securityContext:
#            privileged: true
      {{- if .Values.plugins.install }}
        - name: install-plugins
#          image: {{ default "joosthofman/wget:1.0" .Values.plugins.initContainerImage }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          command: ["sh",
            "-c",
            "mkdir -p /opt/sonarqube/extensions/plugins/tmp &&
            rm -f /opt/sonarqube/extensions/plugins/tmp/* &&
            cp /tmp/scripts/install_plugins.sh /opt/sonarqube/extensions/plugins/tmp/install_plugins.sh &&
            chmod 0775 /opt/sonarqube/extensions/plugins/tmp/install_plugins.sh &&
            /opt/sonarqube/extensions/plugins/tmp/install_plugins.sh && pwd && ls -lah
            "
           ]
          volumeMounts:
            - mountPath: /opt/sonarqube/extensions/plugins/tmp
              name: sonarqube
              subPath: tmp
            - mountPath: /opt/sonarqube/data
              name: sonarqube
              subPath: data
            - mountPath: /opt/sonarqube/extensions/downloads
              name: sonarqube
              subPath: downloads
            - mountPath: /opt/sonarqube/extensions/plugins
              name: sonarqube
              subPath: plugins
            - mountPath: /opt/sonarqube/temp
              name: sonarqube
              subPath: temp
            - mountPath: /opt/sonarqube/logs
              name: sonarqube
              subPath: logs
            - name: install-plugins
              mountPath: /tmp/scripts/
          resources:
{{ toYaml .Values.plugins.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
      {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: configure-sonarqube
#          image: centos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
          - name: API_USER
            valueFrom:
              secretKeyRef:
                name: sdp-jenkins-secret
                key: username
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                name: sdp-jenkins-secret
                key: token
          - name: SQ_USER
            valueFrom:
              secretKeyRef:
                name: sonarqube-credential-configuration
                key: username
          - name: SQ_PW
            valueFrom:
              secretKeyRef:
                name: sonarqube-credential-configuration
                key: password
          command: [ "/bin/bash" ]
          args: [ "-c", "until curl -sL -w %{http_code} -u $API_USER:$API_TOKEN http://jenkins.{{ .Values.jenkins.masterNamespace }}.svc:8080 -o /dev/null | grep 200 ; do echo \"waiting on jenkins..\" && sleep 2; done && echo \"waiting on sonarqube...\" && until curl -s -u admin:admin http://localhost:9000/api/system/health | grep -i green ; do echo \"sleeping..\" && sleep 2; done &&    curl -X POST -s -u admin:admin http://localhost:9000/api/users/create?login=$SQ_USER\\&name=user\\&password=$SQ_PW && echo \"fieldValues={\\\"name\\\":\\\"$SQ_USER\\\", \\\"url\\\":\\\"http://jenkins.{{ .Values.jenkins.masterNamespace }}.svc:8080/sonarqube-webhook/\\\"}\" > /tmpDir/json && curl -v -X POST -u admin:admin http://localhost:9000/api/settings/set?key=sonar.webhooks.global --data @/tmpDir/json && echo \"completed script...\" && tail -f /dev/null"]
          volumeMounts:
            - mountPath: /tmpDir
              name: tmp-dir
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- if .Values.plugins.install }}
          command:
            - /tmp/scripts/copy_plugins.sh
          {{- end }}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            - name: API_USER
              valueFrom:
                secretKeyRef:
                  name: sdp-jenkins-secret
                  key: username
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sdp-jenkins-secret
                  key: token
            - name: SQ_USER
              valueFrom:
                secretKeyRef:
                  name: sonarqube-credential-configuration
                  key: username
            - name: SQ_PW
              valueFrom:
                secretKeyRef:
                  name: sonarqube-credential-configuration
                  key: password
            - name: SONARQUBE_JDBC_USERNAME
              {{- if eq .Values.database.type "postgresql" }}
              value: {{ .Values.postgresql.postgresUser | quote }}
              {{- else if eq .Values.database.type "mysql" }}
              value: {{ .Values.mysql.mysqlUser | quote }}
              {{- end }}
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if eq .Values.database.type "postgresql" }}
                  name: {{- if .Values.postgresql.enabled }} {{ template "postgresql.fullname" .}} {{- else if .Values.postgresql.postgresPasswordSecret }} {{ .Values.postgresql.postgresPasswordSecret }} {{- else }} {{ template "sonarqube.fullname" . }} {{- end }}
                  key: postgres-password
                  {{- else if eq .Values.database.type "mysql" }}
                  name: {{- if .Values.mysql.enabled }} {{ template "mysql.fullname" .}} {{- else if .Values.mysql.mysqlPasswordSecret }} {{ .Values.mysql.mysqlPasswordSecret }} {{- else }} {{ template "sonarqube.fullname" . }} {{- end }}
                  key: mysql-password
                  {{- end }}
            - name: SONARQUBE_JDBC_URL
              {{- if eq .Values.database.type "postgresql" }}
              value: "jdbc:postgresql://{{ template "postgresql.hostname" . }}:{{- .Values.postgresql.service.port -}}/{{- .Values.postgresql.postgresDatabase -}}"
              {{- else if eq .Values.database.type "mysql" }}
              value: "jdbc:mysql://{{ template "mysql.hostname" . }}:{{ .Values.mysql.service.port }}/{{ .Values.mysql.mysqlDatabase }}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true{{- range $key, $value := .Values.mysql.mysqlParams }}&{{ $key }}={{ $value }}{{- end }}"
              {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.sonarWebContext }}sessions/new
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.sonarWebContext }}sessions/new
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          volumeMounts:
            {{- if .Values.sonarProperties }}
            - mountPath: /opt/sonarqube/conf/
              name: config
            {{- end }}
            - mountPath: /opt/sonarqube/data
              name: sonarqube
              subPath: data
            - mountPath: /opt/sonarqube/extensions/plugins/tmp
              name: sonarqube
              subPath: tmp
            - mountPath: /opt/sonarqube/extensions/downloads
              name: sonarqube
              subPath: downloads
            - mountPath: /opt/sonarqube/extensions/plugins
              name: sonarqube
              subPath: plugins
            - mountPath: /opt/sonarqube/temp
              name: sonarqube
              subPath: temp
            - mountPath: /opt/sonarqube/logs
              name: sonarqube
              subPath: logs
            - mountPath: /tmp
              name: tmp-dir
            - name: copy-plugins
              mountPath: /tmp/scripts
            - name: patch
              mountPath: /opt/sonarqube/bin
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.sonarProperties }}
      - name: config
        configMap:
          name: {{ template "sonarqube.fullname" . }}-config
          items:
          - key: sonar.properties
            path: sonar.properties
      {{- end }}
      - name: install-plugins
        configMap:
          name: {{ template "sonarqube.fullname" . }}-install-plugins
          items:
            - key: install_plugins.sh
              path: install_plugins.sh
      - name: copy-plugins
        configMap:
          name: {{ template "sonarqube.fullname" . }}-copy-plugins
          defaultMode: 0755
          items:
            - key: copy_plugins.sh
              path: copy_plugins.sh
      - name: patch
        configMap:
          name: {{ template "sonarqube.fullname" . }}-patch
          defaultMode: 0777
          items:
            - key: run.sh
              path: run.sh
      - name: sonarqube
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "sonarqube.fullname" . }}{{- end }}
        {{- else }}
        emptyDir: {}
        {{- end  }}
      - name : tmp-dir
        emptyDir: {}
