# Copyright © 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-credential-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
data:
    username: {{ .Values.username | b64enc | quote }}
    password: {{ .Values.password | b64enc | quote }}
