
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.sonarProperties }}
  sonar.properties:
  {{ range $key, $val := .Values.sonarProperties }}
    {{ $key }}={{ $val }}
  {{ end }}
  {{- end }}
