####ECS Cluster Nested Template for SDP-Master 
####Missing Requirements
####Subnets and a Security group need to be created and referenced.
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: List<AWS::EC2::Subnet::Id>
  DesiredCapacity:
    Type: Number
  MaxSize:
    Type: Number
    Description: Maximum number of instances that can be launched in your ECS cluster.
  InstanceType:
    Description: EC2 instance type
    Type: String
  InstanceProfile:
    Type: String
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the machine instances.
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
    Default: bdso-def
  ClusterSecurityGroup:
    Type: List<AWS::EC2::SecurityGroup::Id>
Mappings:
  AWSRegionToAMI:
    us-east-1:
      AMIID: ami-0fac5486e4cff37f4
    us-east-2:
      AMIID: ami-0dca97e7cde7be3d5
    us-west-1:
      AMIID: ami-9fadf8ff
    us-west-2:
      AMIID: ami-7abc111a
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: 'SDPECSCluster'
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref 'SubnetId'
      LaunchConfigurationName: !Ref 'ContainerInstances'
      MinSize: '1'
      MaxSize: !Ref 'MaxSize'
      DesiredCapacity: !Ref 'DesiredCapacity'
    #CreationPolicy:
    #  ResourceSignal:
    #    Timeout: PT15M
    #UpdatePolicy:
    #  AutoScalingReplacingUpdate:
    #    WillReplace: 'true'
  ContainerInstances:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', AMIID]
      SecurityGroups: !Ref ClusterSecurityGroup
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource ECSAutoScalingGroup --region ${AWS::Region}
Outputs:
  SDPCluster:
    Value: !GetAtt ECSCluster.Arn